trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'  # Path to your Gradle wrapper
    tasks: 'build'  # Replace with the tasks you want to run
    publishJUnitResults: true
    testResultsFiles: '**/test-results/**/*.xml'  # Updated pattern for test result files
